import Head from "next/head";
import CostumeCarousel from "../components/CostumeCarousel";
import WeatherTable from "../components/WeatherTable";
import { GetServerSideProps, NextPage } from "next";
import { WeatherType } from "./type/type";

interface Props {
  data: WeatherType
}
const HomePage:NextPage<Props> = ({data}) => {
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="row" style={{ paddingTop: `100px` }}>
        <div className="container">
          <div className="row">
            <div className="col-10 offset-1 text-center">
              <h2>Welcome to the playground</h2>
              <p className="font-weight-bold h4">
                Scroll down to dim the light
              </p>
            </div>
            <div className="col-10 offset-1 text-start">
              <p style={{ color: `#e6e6fa` }}>
                In the enchanting realm of lo-fi, a musical universe emerges,
                creating a serene sanctuary for the weary souls seeking solace
                in its gentle melodies. A subgenre of ambient music, lo-fi (low
                fidelity) is characterized by its soothing, often instrumental
                tunes that evoke a sense of tranquility and nostalgia. It
                thrives on imperfections, celebrating the warmth of analog sound
                and the crackling ambiance of vinyl. In this lo-fi world,
                downtempo beats weave a tapestry of relaxation, transporting
                listeners to a realm where time slows down. The rhythmic cadence
                of lo-fi serves as a therapeutic escape, embracing simplicity
                and understated beauty. Its unassuming nature belies a profound
                impact, providing a sonic refuge from the chaos of modern life.
                Embraced by a global community, lo-fi is not just a genre; it's
                a culture. Streaming platforms and social media have become
                conduits for the sharing of carefully curated lo-fi playlists,
                fostering a sense of connection among listeners worldwide.
                Whether as a backdrop for studying, working, or simply
                unwinding, lo-fi has carved out a niche in the hearts of those
                who seek harmony in its gentle hum. In the lo-fi world, time
                stands still, and the subtle melodies become a companion for
                introspection—a reminder that amidst the hustle and bustle,
                there exists a tranquil sanctuary where simplicity reigns
                supreme. I don't know what else to say so im writing something
                just to fill-up the space if you're reading this far I hope you
                have a lovely day/night. Lorem ipsum dolor sit, amet consectetur
                adipisicing elit. Assumenda, ab eum a necessitatibus earum,
                expedita quae odit temporibus corporis libero quas aperiam rem
                sit eligendi consequatur. Minus quae accusamus officia
                perspiciatis. Esse reiciendis deserunt fuga amet. Illo error et
                ratione quis quia necessitatibus at? Sed delectus quod
                dignissimos perspiciatis itaque odit error aliquid laborum vel.
              </p>

              <h2>That's more like it !</h2>
              <p>Now lets see the carousel</p>
            </div>
          </div>
          <div className="row py-5">
            <div className="col-10 offset-1">
              <CostumeCarousel />
            </div>
          </div>
          <div className="row py-5">
            <div className="col-8 offset-2">
              <h2>Weather condition</h2>
              <p>Not your city? Well bud search it up bellow!</p>
              <WeatherTable data= {data} />
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
export default HomePage

export const getServerSideProps: GetServerSideProps = async ({ query }) => {
  let data: WeatherType | undefined;
  if (query.q) {
    const res = await fetch(
      `https://api.openweathermap.org/data/2.5/weather?q=${query.q}&appid=3cf9d39005c56311a8b28a452a6e2126`
    );
    data = await res.json();
  } else {
    const res = await fetch(
      `https://api.openweathermap.org/data/2.5/weather?q=Veles&appid=3cf9d39005c56311a8b28a452a6e2126`
    );
    data = await res.json();
  }

  return {
    props: {
      data: data,
    },
  };
};
