import Head from "next/head";
import { GetServerSideProps, NextPage } from "next";
import { ProductType } from "@/type/type";
import MainPageHeartPill from "@/components/mainPageHeartPill";
import LandingPageCardOne from "@/components/LandingPageCardOne";
import LandingPageCardTwo from "@/components/LandingPageCardTwo";
import MainPagePhotoSlider from "@/components/MainPagePhotoSlider";

interface Props {
  dataRes: ProductType[];
}

const HomePage: NextPage<Props> = ({ dataRes }) => {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LandingPageCardOne />
      <MainPagePhotoSlider data={dataRes} />
      <LandingPageCardTwo />
      <MainPageHeartPill />
    </>
  );
};

export default HomePage;

export const getServerSideProps: GetServerSideProps = async () => {
  const res = await fetch(
    `http://localhost:5001/Igralishteskopje?_start=0&_limit=3`
  );
  const dataRes: ProductType[] = await res.json();

  return {
    props: {
      dataRes: dataRes,
    },
  };
};
