import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Banner from "../components/Banner";
import CategoryPicker from "../components/CategoryPicker";
import FeaturedBlogs from "../components/FeaturedBlogs";
import FeaturedProducts from "../components/FeaturedProducts";
import { FeaturedBlogsType, ProductsType } from "../type/type";
import { useRouter } from "next/router";

interface BannerType {
  preTitle: string;
  title: string;
}

interface Props {
  dataBanner: BannerType;
  dataFeaturedProducts: ProductsType[],
  dataFeaturedBlogs: FeaturedBlogsType[]
}

const Home: NextPage<Props> = ({ dataBanner,dataFeaturedProducts,dataFeaturedBlogs }) => {
const router = useRouter()
console.log(router)
const handleFilterGender = (gender:string) => {
  router.push({
    pathname: `/shop`,
    query: {
      gender: gender,
    },
  });
}

  return (
    <>
      <Head>
        <title>Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Banner title={dataBanner.title} preTitle={dataBanner.preTitle} />

      <CategoryPicker handleFilterGender={handleFilterGender} />

      <FeaturedProducts data= {dataFeaturedProducts} />

      <FeaturedBlogs data={dataFeaturedBlogs}/>
    </>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async () => {

  const resBanner = await fetch(`http://localhost:5001/banner_content`);
  const dataBanner:BannerType = await resBanner.json();

  const resFeaturedProducts = await fetch(`http://localhost:5001/products/?_limit=4`);
  const dataFeaturedProducts:ProductsType[] = await resFeaturedProducts.json();

  const resFeaturedBlogs = await fetch(`http://localhost:5001/blogs/?_limit=3`);
  const dataFeaturedBlogs:FeaturedBlogsType[] = await resFeaturedBlogs.json();

  return {
    props: {
      dataBanner: dataBanner,
      dataFeaturedProducts:dataFeaturedProducts,
      dataFeaturedBlogs:dataFeaturedBlogs
    },
  };
};

