import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import React, { ChangeEvent, useRef } from "react";
import BlogItem from "../../components/BlogItem";
import PageTitle from "../../components/PageTitle";
import { useRouter } from "next/router";
import { FeaturedBlogsType } from "../../type/type";

interface Props {
  dataBlog: FeaturedBlogsType[];
}

const Blog: NextPage<Props> = ({ dataBlog }) => {
  const router = useRouter();
  const inputRef = useRef<HTMLInputElement>(null);
  console.log(router);
  return (
    <>
      <Head>
        <title>Store - Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageTitle title="Blog" />

      <section className="bg0 p-t-62 p-b-60">
        <div className="container">
          <div className="row">
            <div className="col-md-8 col-lg-9 p-b-80">
              <div className="p-r-45 p-r-0-lg">
                {dataBlog.length > 0 ? (
                  dataBlog.map((blog) => {
                    return <BlogItem {...blog} key={blog.id} />;
                  })
                ) : (
                  <p>There are no results with your search.</p>
                )}
                {/*  */}
              </div>
            </div>

            <div className="col-md-4 col-lg-3 p-b-80">
              <div className="side-menu">
                <form
                  className="bor17 of-hidden pos-relative"
                  onSubmit={(event: React.FormEvent<HTMLFormElement>) => {
                    event.preventDefault();
                    {
                      inputRef.current?.value === ""
                        ? router.push({
                            pathname: "/blog",
                          })
                        : router.push({
                            pathname: "/blog",
                            query: {
                              ...router.query,
                              q: inputRef.current?.value,
                            },
                          });
                    }
                    inputRef.current!.value = "";
                  }}
                >
                  <input
                    className="stext-103 cl2 plh4 size-116 p-l-28 p-r-55"
                    type="text"
                    name="search"
                    placeholder="Search"
                    ref={inputRef}
                  />

                  <button
                    className="flex-c-m size-122 ab-t-r fs-18 cl4 hov-cl1 trans-04"
                    type="submit"
                  >
                    <i className="zmdi zmdi-search"></i>
                  </button>
                </form>

                <div className="p-t-55">
                  <h4
                    style={{ cursor: `pointer` }}
                    className="mtext-112 cl2 p-b-33"
                    onClick={() => {
                      router.replace({
                        pathname: `/blog`,
                        query: {},
                      });
                    }}
                  >
                    Categories
                  </h4>

                  <ul>
                    <li className="bor18">
                      <button
                        className="dis-block stext-115 cl6 hov-cl1 trans-04 p-tb-8 p-lr-4"
                        onClick={() => {
                          router.push({
                            pathname: `/blog`,
                            query: {
                              ...router.query,
                              category: `fashion`,
                            },
                          });
                        }}
                      >
                        Fashion
                      </button>
                    </li>

                    <li className="bor18">
                      <button
                        className="dis-block stext-115 cl6 hov-cl1 trans-04 p-tb-8 p-lr-4"
                        onClick={() => {
                          router.push({
                            pathname: `/blog`,
                            query: {
                              ...router.query,
                              category: `beauty`,
                            },
                          });
                        }}
                      >
                        Beauty
                      </button>
                    </li>

                    <li className="bor18">
                      <button
                        className="dis-block stext-115 cl6 hov-cl1 trans-04 p-tb-8 p-lr-4"
                        onClick={() => {
                          router.push({
                            pathname: `/blog`,
                            query: {
                              ...router.query,
                              category: `streetstyle`,
                            },
                          });
                        }}
                      >
                        Street Style
                      </button>
                    </li>

                    <li className="bor18">
                      <button
                        className="dis-block stext-115 cl6 hov-cl1 trans-04 p-tb-8 p-lr-4"
                        onClick={() =>
                          router.push({
                            pathname: `/blog`,
                            query: {
                              ...router.query,
                              category: `lifestyle`,
                            },
                          })
                        }
                      >
                        Life Style
                      </button>
                    </li>

                    <li className="bor18">
                      <button
                        className="dis-block stext-115 cl6 hov-cl1 trans-04 p-tb-8 p-lr-4"
                        onClick={() =>
                          router.push({
                            pathname: `/blog`,
                            query: {
                              ...router.query,
                              category: `diy`,
                            },
                          })
                        }
                      >
                        DIY & Crafts
                      </button>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
};

export default Blog;

export const getServerSideProps: GetServerSideProps = async ({ query }) => {
  let res;

  if (query.q && query.category) {
    res = await fetch(
      `http://localhost:5001/blogs?category_like=${query.category}&q=${query.q}`
    );
  } else if (query.q) {
    res = await fetch(`http://localhost:5001/blogs?q=${query.q}`);
  } else if (query.category) {
    res = await fetch(
      `http://localhost:5001/blogs?category_like=${query.category}`
    );
  } else {
    res = await fetch(`http://localhost:5001/blogs`);
  }

  const dataBlog: FeaturedBlogsType[] = await res?.json();

  return {
    props: {
      dataBlog: dataBlog,
    },
  };
};
